"""Added Project table and relationship to Session

Revision ID: 008f4edb6d4f
Revises: aa4efa7fbfd4
Create Date: 2022-04-03 19:56:20.096672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "008f4edb6d4f"
down_revision = "aa4efa7fbfd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.add_column(
        "session", sa.Column("project_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "session", "project", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session", type_="foreignkey")
    op.drop_column("session", "project_id")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
