"""user and session table

Revision ID: 8894927de106
Revises: 
Create Date: 2022-02-11 16:41:11.151151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8894927de106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_created'), 'session', ['created'], unique=False)
    op.create_index(op.f('ix_session_edited'), 'session', ['edited'], unique=False)
    op.create_index(op.f('ix_session_endtime'), 'session', ['endtime'], unique=False)
    op.create_index(op.f('ix_session_explanation'), 'session', ['explanation'], unique=False)
    op.create_index(op.f('ix_session_level'), 'session', ['level'], unique=False)
    op.create_index(op.f('ix_session_name'), 'session', ['name'], unique=False)
    op.create_index(op.f('ix_session_starttime'), 'session', ['starttime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_starttime'), table_name='session')
    op.drop_index(op.f('ix_session_name'), table_name='session')
    op.drop_index(op.f('ix_session_level'), table_name='session')
    op.drop_index(op.f('ix_session_explanation'), table_name='session')
    op.drop_index(op.f('ix_session_endtime'), table_name='session')
    op.drop_index(op.f('ix_session_edited'), table_name='session')
    op.drop_index(op.f('ix_session_created'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
