"""skill and many-to-many rel. to sessions tables

Revision ID: aa4efa7fbfd4
Revises: 8894927de106
Create Date: 2022-02-11 16:56:24.018846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa4efa7fbfd4'
down_revision = '8894927de106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_explanation'), 'skill', ['explanation'], unique=False)
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=False)
    op.create_table('bridge_session_skill',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridge_session_skill')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_index(op.f('ix_skill_explanation'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
