"""empty message

Revision ID: abf922d71cfa
Revises:
Create Date: 2022-04-12 01:36:46.728364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abf922d71cfa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_name"), "skill", ["name"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=True
    )
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("edited", sa.DateTime(), nullable=False),
        sa.Column("starttime", sa.DateTime(), nullable=False),
        sa.Column("endtime", sa.DateTime(), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_created"), "session", ["created"], unique=False
    )
    op.create_index(
        op.f("ix_session_edited"), "session", ["edited"], unique=False
    )
    op.create_index(
        op.f("ix_session_endtime"), "session", ["endtime"], unique=False
    )
    op.create_index(
        op.f("ix_session_level"), "session", ["level"], unique=False
    )
    op.create_index(op.f("ix_session_name"), "session", ["name"], unique=False)
    op.create_index(
        op.f("ix_session_starttime"), "session", ["starttime"], unique=False
    )
    op.create_table(
        "bridge_session_skill",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "skill_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bridge_session_skill")
    op.drop_index(op.f("ix_session_starttime"), table_name="session")
    op.drop_index(op.f("ix_session_name"), table_name="session")
    op.drop_index(op.f("ix_session_level"), table_name="session")
    op.drop_index(op.f("ix_session_endtime"), table_name="session")
    op.drop_index(op.f("ix_session_edited"), table_name="session")
    op.drop_index(op.f("ix_session_created"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_skill_name"), table_name="skill")
    op.drop_table("skill")
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_table("project")
    # ### end Alembic commands ###
